### ISSUE TITLE
Mac/Linux脚本报错

### ISSUE THREAD

**Issue by Xxx00xxX33** [miracleyoo/anime_renamer#1]
大佬 可以请教一下我运行rename_episodes.sh 之后报错， 信息如下：

File "/home/reg_match.py", line 16
SyntaxError: Non-ASCII character '\xe7' in file /home/reg_match.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

我在mac，群晖还有ubuntu上都试了都是一样的报错，是我哪里没弄对吗

**Comment by Seeger0216** [comment]
换成python3

**Comment by Xxx00xxX33** [comment]
> 换成python3

谢谢大佬~
